[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["cd client && npm install && npm run build && cd .."]

[start]
cmd = "node --experimental-sqlite server/index.js"
